# Generated from packaging/homebrew/tflint.rb.in by `mise run homebrew:render`.
# Edit the template, not this file.
# Originally generated by GoReleaser (terraform-linters/homebrew-tap).
cask "tflint" do
  version "0.64.0"

  on_macos do
    on_arm do
      sha256 "2496e9cb3d24992d553b45e7c87a0fdc9449ca975233876247a9bfeda857e6c0"
      url "https://github.com/terraform-linters/tflint/releases/download/v#{version}/tflint_darwin_arm64.zip"
    end
    on_intel do
      sha256 "0f3a9fd17526014646a2dfc3f9122f7b4161abe3d6b0f0f03f9014483ddf4d19"
      url "https://github.com/terraform-linters/tflint/releases/download/v#{version}/tflint_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "560da89aacf59389d4eb029730dd5b109b7288096c32f2726a0d9e783a5ea8eb"
      url "https://github.com/terraform-linters/tflint/releases/download/v#{version}/tflint_linux_arm64.zip"
    end
    on_intel do
      sha256 "cca9d13e2e1d7a2c627af60ff899a3c9b74212899416aeb96ec764d2ef954537"
      url "https://github.com/terraform-linters/tflint/releases/download/v#{version}/tflint_linux_amd64.zip"
    end
  end

  name "TFLint"
  desc "Pluggable Terraform linter"
  homepage "https://github.com/terraform-linters/tflint"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "tflint"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/tflint"]
    end
  end

  # No zap stanza required
end
